### ISSUE TITLE
Shouldn't beautify org-mode files

### ISSUE THREAD

**Issue by shackra** [yasuyk/web-beautify#12]
I save my configuration in a org-mode file. when I do some change, I re-load it with <kbd>M-x</kbd> `load-file` <kbd>RET</kbd> `~/.emacs.d/init.el`. If I add or remove text from my org file and save it, web-beautify beautifies that file!

```
Loading /home/jorge/.emacs.d/emacs-init.el (source)...
Loading /home/jorge/.emacs.d/paquetes.el (source)...done
Loading /home/jorge/.emacs.d/site-packages/golang/company-go.el (source)...done
Loading /home/jorge/.emacs.d/site-packages/erosiond-theme/erosiond-theme.el (source)...done
Loading /home/jorge/.emacs.d/site-packages/u-vm-color/u-vm-color.el (source)...done
Loading /home/jorge/.emacs.d/custom.el (source)...done
Loading /home/jorge/.emacs.d/mu4e-conf.secret.gpg...
Decrypting /home/jorge/.emacs.d/mu4e-conf.secret.gpg...done
Loading /home/jorge/.emacs.d/mu4e-conf.secret.gpg...done
[sml] sml/theme set to respectful
Loading /home/jorge/.emacs.d/emacs-init.el (source)...done
Saving file /home/jorge/.emacs.d/emacs-init.org...
Wrote /tmp/web-beautify8266lci.html
Applied web-beautify
Wrote /home/jorge/.emacs.d/emacs-init.org
```

I have set the `before-save-hook` to call `web-beautify-html-buffer` in [my configuration](https://github.com/shackra/.emacs.d/blob/master/emacs-init.org#gancho-para-antes-de-guardar-el-archivo)

**Comment by yasuyk** [comment]
Sorry for the very very delayed response.
I check [emacs-init.org](https://github.com/shackra/.emacs.d/blob/0c019b830c1f460ff3d2397ef14ba7ad1feb7efc/emacs-init.org) at that time. You used add-hook directly in emacs org-mode, so web-beautify applied to emacs-init.org. As you know, your latest init.el is already fixed. I'm closing this issue.
