### ISSUE TITLE
Add hook for web-mode.el

### ISSUE THREAD

**Issue by Immortalin** [yasuyk/web-beautify#16]
Can a format-on-save hook example be added for web-mode.el?

**Comment by yasuyk** [comment]
@Immortalin Sorry for the very very delayed response. 
I update README for web-mode configuration. 3eecd38b90b0e215f6a8ba69a7139c80f4b1a600

**Comment by yasuyk** [comment]
Closing this. Please reopen if necessary.

**Comment by Immortalin** [comment]
@yasuyk thanks
