### ISSUE TITLE
web-beautify mark behavior on emacs 25

### ISSUE THREAD

**Issue by j-em** [yasuyk/web-beautify#20]
![image](https://cloud.githubusercontent.com/assets/943725/14734164/a1ad2eac-0836-11e6-9bfe-b1e4278ca072.png)

The mark is behaving weirdly after using the function to format JS.

I think the problem is here: https://github.com/yasuyk/web-beautify/blob/master/web-beautify.el#L121

When I removed that line, everything was fine except for the broken syntax highlighting when using web-mode.

**Comment by lukertty** [comment]
I have the same problem.

I also removed that line..

**Comment by yasuyk** [comment]
@j-em @lukertty Could you  let me know following the information?
- OS and version
- node version
- js-beautify version

I can not reproduce this issue. 😰

**Comment by lukertty** [comment]
@yasuyk 

* OS and version : macOS 10.12.2 beta (16C32f), Emacs 25.1
* node version : 7.0.0
* js-beautify version : 1.6.4
* web-beautify version : 20160410.1005
* js2-mode version : 20161025.1012

Before removing `(web-beautify-reload)`

![1](https://cloud.githubusercontent.com/assets/11374295/20046335/6b89cd4a-a4e3-11e6-80de-d485b40c2845.gif)

After removing `(web-beautify-reload)`

![2](https://cloud.githubusercontent.com/assets/11374295/20046334/6b894a32-a4e3-11e6-9632-0fc8300b8da8.gif)

If I replace `(web-beautify-reload)`  with`(js2-mode)`, the issue can be reproduced,  but if I just run `js2-mode` in main.js file, then there is no problem.

😳

**Comment by vxcamiloxv** [comment]
Same here:

- OS and version : Parabola Gnu/Linux, Emacs 25.1
- node version : 7.1.0
- js-beautify version : 1.6.4
- web-beautify version : 20160410.1005
- js2-mode version : 20161025.1012

**Comment by yasuyk** [comment]
@lukertty, @vxcamiloxv  Thank you for information. I reproduce this issue. I use emacs with no window, in other words, use emacs in Terminal. This issue is not occurred on emacs in Terminal.

**Comment by yasuyk** [comment]
This issue is fixed at 50bc8cb. If something wrong occurs, Reopen this issue.

**Comment by vxcamiloxv** [comment]
thanks
