### ISSUE TITLE
"Could not apply web-beautify. See *Web Beautify Errors* to for details."

### ISSUE THREAD

**Issue by MatMercer** [yasuyk/web-beautify#21]
Hi, I installed this package using the package manager and when I key-bind it to C-b c it displays a message and doesn't work!

I don't know what is causing it and the _Web Beautify Errors_ buffer is empty!

I've installed js-beautify with NPM already.

**Comment by andrew-kennedy** [comment]
I have this same problem. Js-beautify works on its own when run against the file through terminal. The error buffer is empty for me as well.

**Comment by MrAnyone** [comment]
Now, after trying to make it work, calling the package deletes all the characters in the current Js file.

**Comment by vspinu** [comment]
Same errors here with   "/usr/bin/env: ‘node’: No such file or directory" in the error buffer. Fixed by installing `nodejs-legacy` package. The executable should be `nodejs` I would guess.

**Comment by yasuyk** [comment]
@MrAnyone @andrew-kennedy Sorry for the late reply. If you still interested in this issue, let me know following the information.

- OS and version
- node version
- js-beautify version

**Comment by MrAnyone** [comment]
Since I changed my setup in the mean time, the only information I can give you is that:
* Linux Mint 14.7
* Latest Emacs 25.X in the date (I've compiled it myself).

Thanks for the response, good luck solving this problem!

**Comment by yasuyk** [comment]
@MrAnyone Thank you for the response. Could you let me know node version and js-beautify version?

**Comment by MrAnyone** [comment]
Ok, it may not be 100% accurate, since I stopped using it ~2 months ago
* The node was from nodejs package (installed through apt-get)
* js-beautify was the latest to the date (installed through npm)

I didn't noticed any updated from nodejs so probably it is still in the same version.

**Comment by MrAnyone** [comment]
There is a "trick" where you create a symlink to fix the nodejs name.
```shell
sudo ln -s /usr/bin/nodejs /usr/bin/node
```

This *may* fix the problem.

**Comment by yasuyk** [comment]
@MatMercer @vspinu @andrew-kennedy It seems a problem of `nodejs package`. See nodejs/node-v0.x-archive#3911.

**Comment by MatMercer** [comment]
@yasuyk I thought so, at the time I didn't come out with this solution but it should fix the problem.
I'm closing this issue for now, since making a symlink should fix the problem.

Thanks for all the support.

**Comment by yasuyk** [comment]
@MatMercer You’re welcome.
