### ISSUE TITLE
web-beautify not working for html / css

### ISSUE THREAD

**Issue by der-Daniel** [yasuyk/web-beautify#22]
Hi,

I have installed `js-beautify` via npm.
In emacs running `web-beautify-js` works just fine, but using `..-html` or `..-css` give me the error that `[html/css]-beautify not found. Install it with 'npm -g install js-beautify'.`

How do I solve this?

For Frodo
Daniel

**Comment by yasuyk** [comment]
@der-Daniel Hi,

`web-beautify-html` use `html-beautify` command and `web-beautify-css` use `css-beautify` command. It seems that `html-beautify` and `css-beautify` are not found in your PATH.
These command are installed with `js-beautify` like this:

```
 $ npm install -g  js-beautify
/Users/yasuyk/.nvm/versions/node/v5.10.0/bin/css-beautify -> /Users/yasuyk/.nvm/versions/node/v5.10.0/lib/node_modules/js-beautify/js/bin/css-beautify.js
/Users/yasuyk/.nvm/versions/node/v5.10.0/bin/html-beautify -> /Users/yasuyk/.nvm/versions/node/v5.10.0/lib/node_modules/js-beautify/js/bin/html-beautify.js
/Users/yasuyk/.nvm/versions/node/v5.10.0/bin/js-beautify -> /Users/yasuyk/.nvm/versions/node/v5.10.0/lib/node_modules/js-beautify/js/bin/js-beautify.js
/Users/yasuyk/.nvm/versions/node/v5.10.0/lib
└─┬ js-beautify@1.6.2
  ├─┬ config-chain@1.1.10
  │ ├── ini@1.3.4
  │ └── proto-list@1.2.4
  ├─┬ mkdirp@0.5.1
  │ └── minimist@0.0.8
  └─┬ nopt@3.0.6
    └── abbrev@1.0.7
```

Please confirm your PATH.

**Comment by der-Daniel** [comment]
Thanks, I was actually just blind :see_no_evil: 

I thought calling `html-beautify` was just `js-beautify` with a parameter. Did no know that this installed a separate binary..

Thanks
