### ISSUE TITLE
[request] Configuration sample for a predefined coding standard

### ISSUE THREAD

**Issue by Dragnucs** [yasuyk/web-beautify#25]
Please proivd either as a default or in the docs and configuration to force all codes, especially JavaScript, to follow a popular coding standard.

I am myself not familiar with ECMAScript good practices and a tool like this would help me a lot.

**Comment by yasuyk** [comment]
@Dragnucs  I use C, C++ and Java for earning money and use JavaScript a little for the hobby. So I 'm not familiar with ECMAScript good practices too.  I cannot help you. 😓

**Comment by Dragnucs** [comment]
[Standardjs](https://standardjs.com/) is the standard.
