### ISSUE TITLE
js-beautify as a node library(install locally)

### ISSUE THREAD

**Issue by am-1t** [yasuyk/web-beautify#35]
I installed js-beautify locally in my project directory.
Is there a way to make it work with web-beautify?
When I run M-x web-beautify-js , it says js-beautify not found and asks to install it globally.
Thank You

**Comment by tulsileathers** [comment]
I have a similar question. Is there a way a variable which sets the js-beautify executable? This could be configured to use the js-beautify in the local node_modules folder. 
```
